USE [ZEUS]

GO


select * from CARGOS

select * from  CLASESHUESPEDES

select * from CLIENTES

select * from ESTAD_HIS order by FECHA desc

select * from  MOVFOLIO WHERE CLASE = 'M' order by FECHA desc

select * from ESTAD_HIS 
where REGISTRO=000280

select * from CLIENTES
where NOMBRE_CLI like '%ANDERSON%' 

--WHERE IDENT_CLI = 'G000000000350' 

select * from REGISTRO
where REGISTRO=000280

select * from ESTADSALDOFOLIOS
where NFOLIO=000280


--Master
select C.DESCRI_CAR ,  M.* 
from [dbo].[MOVFOLIO] M
INNER JOIN  [dbo].[CARGOS] C ON M.CCARGO_CAR = C.CCARGO_CAR
where NFOLIO=000280 AND year (FECHA) = 2010 AND CLASE='M'
order by FECHATRA desc, NFOLIO


--Extras
select C.DESCRI_CAR ,  M.* 
from [dbo].[MOVFOLIO] M
INNER JOIN  [dbo].[CARGOS] C ON M.CCARGO_CAR = C.CCARGO_CAR
where NFOLIO=000053 AND year (FECHA) = 2019 AND CLASE='E'
order by FECHA desc, NFOLIO



select * from MAEFOLIO
where NFOLIO = 000280

select F.NOMBRE, M.NFOLIO, M.FECHA, M.MOTIVO, M.TIQUETE,
CASE WHEN M.DBCR = 'D'  THEN M.VALOR ELSE M.VALOR * -1 END AS VALOR,
CASE WHEN M.DBCR = 'D'  THEN M.IVA ELSE M.IVA * -1 END AS IVA,
CASE WHEN M.DBCR = 'D'  THEN VALOR + IVA  ELSE (VALOR + IVA) * -1 END  AS TOTAL 
--SUM (SUM(TOTAL)) OVER (order by M.FECHA asc) AS SALDO
from [dbo].[MOVFOLIO] M WITH(NOLOCK)
INNER JOIN [dbo].MAEFOLIO F  WITH(NOLOCK) ON M.NFOLIO = F.NFOLIO
where M.NFOLIO='000280' AND M.FECHA >= '2010-01-01'  AND M.FECHA <= '2011-12-31' AND CLASE='M'
--GROUP BY M.NFOLIO, M.FECHA, M.MOTIVO, M.TIQUETE, M.DBCR 
order by M.FECHA asc


SELECT F.NOMBRE, M.NFOLIO, M.FECHA, M.CCARGO_CAR, M.MOTIVO, M.TIQUETE,
CASE WHEN M.DBCR = 'D'  THEN M.VALOR ELSE M.VALOR * -1 END AS VALOR,
CASE WHEN M.DBCR = 'D'  THEN M.IVA ELSE M.IVA * -1 END AS IVA,
CASE WHEN M.DBCR = 'D'  THEN VALOR + IVA  ELSE (VALOR + IVA) * -1 END  AS TOTAL 
FROM MOVFOLIO M WITH(NOLOCK)
INNER JOIN MAEFOLIO F  WITH(NOLOCK) ON M.NFOLIO = F.NFOLIO
WHERE M.NFOLIO='000280' 
AND M.FECHA >= '2010-01-01' 
AND M.FECHA <= '2011-12-31' 
AND CLASE='M'
ORDER BY M.FECHA, M.CCARGO_CAR ASC


